language: php

addons:
  apt:
    packages:
    - lftp

env:
  - secure: "TJ1vXgSjS8IWMqyNq7p6HMN6pzQYwHe26cnyr9K3FVOSCPmBlpyREQDIxPsYuStR295Jtvn1fgA9Ab2Z5srPWxirJa+rM43hnxpGHwXdQShMYvUDjw3xIMSjh5peLl7AxTJZc9RN7YfGERKGT/Zc+kU34njRb3TeqNGbcKuEk7Kmi/M/zxsdSYvD8OecrXw2g+2Txwd+/cNTi9pfLP8mXTsIfsmUZb/s7aDEK09UCUo4nnvh8zTtyTlQNYAwArK5gHU4PP70axA8Evo9CBjPWpqOp1b3G7nM8Jotr13M11IeDsvaOyqhgbG8Rs+ds+ukrrEn8IBxG84sUo0kWr+5NftYSqLZuS8ZMzozCchqy/bAJIG7DHb2j8rKZWz41W7qkjdpazVteIdbpP17xEiVH9gkY3jiC0xnVntbmv145EXdvdLacpqOQfTOYp1af4c7HlV/jurDJAISKSI164aFWCAqlAaDFWTy5ex8ijyvG5jFgAL6rAdKH5iaX47eWErigC5KOjErG4tdHxl+revvX7cq5Bphv+eDOtenDXonFkE6I9gj9i8e9/gJ5sYlHslyhLjhAEwXGqwGNiaZLHNkvNc0iAj5ufWK4YmtNYhs3HPwsq0fFq2CSSGOXqnoyrN0TPl5l34BXvWElHN9pkkMmNMUdvx3QrWXsXbxsHkB354="

script:
  - cd tests/moduulitestit && phpunit . && cd ../jarjestelmatestit
  - mvn test & cd ../..

after_success:
  - lftp -e 'mirror --delete -R public_html/ harkkatyo; quit' -u $LOGIN,$PASSWORD $SERVER

notifications:
  - secure: "H1NmWcuyzaGTl9HKe/x17LAcHaGkru/kHgxurFS2liPwYXvNbXiVqNhRr02LBkjR/TZhV5cNbcrOBS2tChUkyBQEJ0iMQK1vszJrg0gViTAhj6sLzWhpM82c2FKk7S6QC7+HMxYRd3Jp8TD7Kwei7uRtv0oL6ZKxPNJ4ZyI2p6lgQ/NUg52OH8G+Tkty2/NWoopS1hnPPfYVDTI9O99prPmCIrIHX0WSmQrOInoTwjgNs3SoQ14Ux+Y+C7cveNt5WcCgct/EryaGxySX5DEV5pAdHjcMEVxdAhTaKbiUynJq371UetGFkLB27weSDcb42iDXX+GxssEIaYQ5Pd4DD3zdTOLsPEdRr8LBA8I7LuetlV4ifIS4D/Vh3HMcWVjhKhPq6N6D51ln+SPe+5u6iJcIL02xN0r/jKu3ob/Y7gKP7vPqVcmVL/l3tSs8Pj/Gr2A2bl4HBABqy7htAlgNwYHa3S8qN0HmYWAGbc5pek0X8J9kE+fY/dyZLOqKDyeSDjmIFFfQgwuOoVNwfvoWZUrR0mF0NDXZ92sM4fQgsSCAz8wZl9SQFTq2rStYcG01MqjUdnHZOEuRiR5HNv1bSR8EttGIjyTrkAZcVyCag/ZoWpmqeDgQCpi4GtkQWyRqRwG1cRCnA6uV6sLFwZHG8L0VUaOlgfjKiTDPwzwdGVk="