language: php

env:
  secure: "Mii1izvJAr29bCN342INlyWh2f9oB8VIN+j29lH5CB0dixzhlxra+DWPr8lHkkaGncgQN0gMJYQ/izZfrbMPZ8Qc+cWSAkLSvuadNCdtWQqQxJS0ZJQdX/kSjp+4P8gmLevvHYqjd/iYaGgdKZqWr899Evs6HLCK9LrCSpjqWu+YycibOviJX3NLplsuqScbOkcWVJGFFthb1l5jeKOGeNJIeU+hVH62wHrUKZKs8ot4oh395xdkmTSfuJrAHQRUSOStbfY/1bAUN5deEiw1rQOKvNo+eYwh5h/BDjIa/2bZcbaMzpiKJrwaCC9PV7CFN9h+udQEaufdsMaFaUnj/KFgGpqH3yBSIMOXc9HBrAkxJWKERcXoRDIAxqY8mbWXRLcCl3NCxWdkoH96t5Kt6An/Wu8ZdNb8upHyJS3e7o83+Vt+iTtx+NwxoreAHWGqqcNya+oNiLmTl4/ZciaH/LKM5vyRfzbnQLbzpGAWbtEXifRTN8NhGJv+fVZEa7sOa1T0vlzYPPoLxzGQMFqxl8eVDlvdoIdyOYe4jQVFZsWTuhM7cjQWERwPFhlxaxQedE+pomwS9BQg91VUN+RscVOqpbZO+MpMHPIF4NF6u+cLYp+ZThEnvT99RloUW5mVR6x/+xm7eU9BtY+pkn3+J2YITbPfcOPfoEQdrP+ZgxA="

script:
  - sh build.sh

notifications:
  slack: titor2:9outGDN2rgdIE01E6LNFuTuF

