language: php

env:
  secure: "ltBKrgeH+07Mu+7ELdXaM4DxEstHe4tPpeXgmkghbnFsaUemQeHkpDgA9cfnARavmfuue0zcR7a9ggXQEu/Df4DgpQLlxpaTzXpGrXSzjbUj734RzJ+X5Iv1Tl2g18uDmtsMmNLz7AjS7rJjZs5pqQRGk85CBg1tPUZwIwqHoEjhZxK1PxhXWLMYbhDW9pPi3z1WintVQNDzpWzNBqXBAU8d9dNIuyKulkrqJjPabYvpqluoiHJQrEmEvFzmqo1kPiqIo/+yKbOaCLmyQbbMhGgfm6xgkJIj7YV7y6AHw9MquhOHSfzgwC0Ex0ztHyB5F2OKNqvehPS1SmieC/rCtheZnjK8buJRoRolNfq6a5gCLgb/HFLQsAH0pCcXLPffLT3BnPxWWvHxIoX58amQzvSFeFYkVMV52yvSM+v8zToLb2MV7b5lHcjtUuyaSA/65aHaf/WLw5H1jrdqGqOE9QUgEsBn9s+ZqmqAgq2ch7i+s5/9igt1gjUM1Inbaf/Z2nUKMxHmgOERAklkZAxaLwmOGD0k3E7SXCFfDvihNq+KXLdIhWLx8j2N2Z19AfMjM/Zme0QaabwI3NI8Bew15zralYGBaShY6e40DAPzH0DOJ9ro7Zffbtf7i2fnTLEA5VwJcaGmP7e8z+teniYNtfgMGyJGOIHqMuz74F1rr0c="

script:
  - cd tests && phpunit .
