language: php

env:
  secure: "jxF/JooigfNHrnZYWdt/MEwyLJH3+ELpxlc6JTjtjQAaRoOBZfZFgM75HnFC1QxEoSwbB7ayCzxDOBHos4hWGJ/PIwOo0dbYB95yxHlkIC+jHsDHJTRYbY9uj4jw9kiwK7f1FNO78jgsCuNTMlJ9IICwOXY+X6GoRpJB8X6Oz6Gbs9mIcI0I8Onzw1XfQ8mJA6BqHCEriEiEWY+IqhgZydl/sZlO0xuSuSZKfJ+j70BT6TCymIgpsH/RKBpajWceb1ysJgPZN4DYKZsggM5nQBDoRjBnH3rDWMYe/bcrmluHLbXiOcOIQC9jWsn1e9ZobuKoTDjIXV+sCUh6Dfs7eqdSy3EyaUbf1smNXmOrVj6ObzI9uWFBaNOp616t/ekyWi/4s0UqVnAPZmHtgcdbdLe8hSqitCDNNJbjEQKWjNJlDh2eSTdNGz603mQOqNtNQaYUqqv08gkmVoaL5u0pBxWK1adURDkgWlQeHJ62XHa7PmgfYI7UfD7zvLlVOqblu0uobsyGM8xXcBr7VzyMSMtUC48G1Z39ZvWgWLV/zvAufiKbcWA9oysek6+1WxSHuBlG/x62RJEzEcsoyd3vx2oE6+WbZdFIubH2lzo+SzFc/5DaNQBF+/4P1YM34H5GDDwomvi0zopiP9WGS8USjLmxdK5n0Jmt2rTgrNofXWY="

script:
  - sh build.sh

notifications:
  slack: titor2:9outGDN2rgdIE01E6LNFuTuF

