language: php

addons:
  apt:
    packages:
    - lftp

env:
  - secure: "TJ1vXgSjS8IWMqyNq7p6HMN6pzQYwHe26cnyr9K3FVOSCPmBlpyREQDIxPsYuStR295Jtvn1fgA9Ab2Z5srPWxirJa+rM43hnxpGHwXdQShMYvUDjw3xIMSjh5peLl7AxTJZc9RN7YfGERKGT/Zc+kU34njRb3TeqNGbcKuEk7Kmi/M/zxsdSYvD8OecrXw2g+2Txwd+/cNTi9pfLP8mXTsIfsmUZb/s7aDEK09UCUo4nnvh8zTtyTlQNYAwArK5gHU4PP70axA8Evo9CBjPWpqOp1b3G7nM8Jotr13M11IeDsvaOyqhgbG8Rs+ds+ukrrEn8IBxG84sUo0kWr+5NftYSqLZuS8ZMzozCchqy/bAJIG7DHb2j8rKZWz41W7qkjdpazVteIdbpP17xEiVH9gkY3jiC0xnVntbmv145EXdvdLacpqOQfTOYp1af4c7HlV/jurDJAISKSI164aFWCAqlAaDFWTy5ex8ijyvG5jFgAL6rAdKH5iaX47eWErigC5KOjErG4tdHxl+revvX7cq5Bphv+eDOtenDXonFkE6I9gj9i8e9/gJ5sYlHslyhLjhAEwXGqwGNiaZLHNkvNc0iAj5ufWK4YmtNYhs3HPwsq0fFq2CSSGOXqnoyrN0TPl5l34BXvWElHN9pkkMmNMUdvx3QrWXsXbxsHkB354="

script:
  - cd tests/moduulitestit && phpunit . && cd ../jarjestelmatestit
  - mvn test & cd ../..

after_success:
  - lftp -e 'mirror --delete -R public_html/ harkkatyo; quit' -u $LOGIN,$PASSWORD $SERVER