language: php

env:
  - secure: "h3ZyS0thQtYfR0OdzwC6c5yrXT4TWSaiUTS4B5rzXHBw3GWy6+umQw1YlfhXxJOlaVBET8YOr5l3+N3ITFuRmDpEdztCnNPxog5ainkWMSBjlwFL7h9kg5I5JfsE0x6Pgmlhm8Eh8KfoZbPAbAHkW6OiFPUlL2RBcCyULF35bLx4NZANGIYZnK+at1+zUyAy+LtAUxxRgex3973BFJQgitLdzISMhlNfwHdAHX8Y6p03SzNRreWhpCggrUZlNZ03WYeCFHsUDB7+z5ZLA+0OXYnnsWLjtbrcOYUUvbTm6NMJm+BJ7tb004fjc3mYmjb9AXa2HnP8Mm5xU8fKXbozu+U3R2duaKZ8XvdIREbZ388zu+T5gZNchOmspFe+0UJDLNMGyIX1hCT18gQQzopbVEOZNu3YqDTxnhNi2WRxF2mFFBLjbzUm3UGHZNDnAe3NnY6f+ALuaeCEb7vr9lqat7Ol1Yu4HUKSWA1/MW6KbAMLWjtIuLO0RFp3YDf1EwBtbBTgMor5c1V9z6LYEV2fPota7DaVxuXAIktFSdOMH00IixqyjzYf8C6tzqxjs18O6xKu0i+I6oKvHnBBPt0nq30iXPs68XaI2isKl9gE5RL0yWnc/+TaKYCv1gv/hxdCrqeCGbA2UgV2zlh4V9VqhZT4iMLIIIULE2N4gaAhoSM="

script:
  - sh build.sh

notifications:
  slack: titor2:9outGDN2rgdIE01E6LNFuTuF

