language: php

addons:
  apt:
    packages:
    - rsync

script:
  #- cd tests && phpunit . && cd ..
  echo "Ei vielä testejä!"

after_success:
  - rsync -avz --delete public_html/ root@37.139.15.227:/var/www/html/harkkatyo