language: php

env:
  secure: "PPPoi3sLfd+6evB6N6jYInadQCvbyT2e1cec8A+GOKU1SaAa25ZtZdeNlOymgFnClAtmZOjNVMCoyEZVtugxce9+DzFtpvI/wnxeBbXLnQxwBF5zDB4g4V/Y0NF768Uto+dAjfdQnz1JyrGE46xAaSB3h59XyHoUzzg34CzoiKaS9p7KHsVIZjAfH6me9c4KRVsbA9U7hlsoz03OyuEoT8ZppnwkLY7ErvYuZy1wB5EUGla3Z14a4PwBHhXw1tN8rGmkF6fiekSw82bQkRTs8BvkYpLIqA8aYrcw24gEvZunf9u6zyEbK307hjU1+H2LueR3JCII3c/TDM6KnGBLHtTqmAtdClbU29LTd+TBFfDixTSAQ23v9GaApNnXYwhGXtEVMbx47JQ5dgXXMYezWA50G9TcVYrRS1+JeUeeash0d9RMR3em3ts63WJh2x4O83OugnyNbJat80ZDKH2gRSyBmj/yuHAzLuzAGGohpq5VbIX8vI5ARKBR0UdO9etC4QR4qtaOKFmZU7DtRVLnUV5IwbzvVJBdL27IPcQ5f3rtc70V22GV/vYMnVDjJQylpwDERisw8fdQO4wiVdgcZd8hapOhruFrR6IAxKCwY2ZJfY1ke0STkG80TktJYFMMbDSdCiUXr4qD4SCeLC4ytRuWSafKiuI8+t/bkWQL1r4="

script:
  - sh build.sh

notifications:
  slack: titor2:9outGDN2rgdIE01E6LNFuTuF

