language: php

before_script:
  - echo -e "Host 37.139.15.227\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

script:
  #- cd tests && phpunit . && cd ..
  echo "Ei vielä testejä!"

after_success:
  - rsync -avz --delete public_html/ buumi@37.139.15.227:/home/buumi/harkkatyo